name: Update README Age

on:
  schedule:
    - cron: "0 0 * * *" # Läuft täglich um Mitternacht UTC
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script to update age
        run: python update_age.py

      - name: Commit and push if changed
        run: |
         git config --global user.name "Nightyonlyy"
         git config --global user.email "business.nightyonly@pm.me"
         git remote set-url origin https://Nightyonlyy:${{ secrets.PAT_TOKEN }}@github.com/Nightyonlyy/Nightyonlyy.git
         git add README.md
         git commit -m "Update age in README" || exit 0
         git push origin main


